"""`spout build-image` — v1-minimal Docker crystallization.

Generates a Dockerfile that pins the current interpreter line, the installed
`rainspout` version, and every installed content package (anything providing
a `rainspout.components` or `rainspout.verbs` entry point) at its installed
version. Nothing cleverer, per the approved v1 scope; editable/local packages
are flagged in a comment for the user to substitute a source line.
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from importlib import metadata


def installed_content_packages() -> dict[str, str]:
    """Distribution name -> version for every installed content package."""
    found: dict[str, str] = {}
    for group in ("rainspout.components", "rainspout.verbs"):
        for entry_point in metadata.entry_points(group=group):
            dist = getattr(entry_point, "dist", None)
            if dist is not None:
                found[dist.name] = dist.version
    return found


def generate_dockerfile() -> str:
    python = f"{sys.version_info.major}.{sys.version_info.minor}"
    rainspout_version = metadata.version("rainspout")
    packages = installed_content_packages()
    pins = " ".join(
        f"{name}=={version}" for name, version in sorted(packages.items()) if name != "rainspout"
    )
    lines = [
        f"# Generated by `spout build-image` at {datetime.now(UTC).isoformat(timespec='seconds')}",
        "# Crystallizes the current environment: rainspout + installed content packages,",
        "# pinned at their installed versions. Editable/local packages appear pinned too —",
        "# replace their pin with a source install line (COPY + pip install) as needed.",
        f"FROM python:{python}-slim",
        f"RUN pip install --no-cache-dir rainspout=={rainspout_version}"
        + (f" {pins}" if pins else ""),
        'ENTRYPOINT ["spout"]',
        "",
    ]
    return "\n".join(lines)
